"use client";
import {FormEvent,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {MessageSquareText,Send} from "lucide-react";
import {Brand} from "@/components/brand";
import {createClient} from "@/lib/supabase/client";
type Row=Record<string,unknown>;
export function ChatPanel({conversations,selected,messages,isAdmin,userId}:{conversations:Row[];selected:string|null;messages:Row[];isAdmin:boolean;userId:string}){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);setBusy(true);setError("");const{error}=await createClient().rpc("send_chat_message",{target_conversation:selected,message_body:String(f.get("body"))});setBusy(false);if(error)return setError(error.message);e.currentTarget.reset();router.refresh();}return <main className="portal-shell chat-shell"><header className="portal-header"><Brand/><Link href="/panel">Volver al panel</Link></header><section className="portal-hero"><p className="eyebrow">COMUNICACIÓN INTERNA</p><h1>Mensajes</h1><p>Conversaciones de texto protegidas dentro de LEGEND CLUB.</p></section><div className="chat-layout"><aside>{conversations.map(c=>{const owner=c.profiles as Row|null;return <Link className={String(c.id)===selected?"active":""} key={String(c.id)} href={`/mensajes?conversation=${String(c.id)}`}><MessageSquareText/><span><strong>{String(owner?.full_name??owner?.email??c.subject)}</strong><small>{String(c.status)}</small></span></Link>})}{!conversations.length&&<p>Sin conversaciones.</p>}</aside><section className="chat-thread"><div className="chat-messages">{messages.map(m=>{const sender=m.profiles as Row|null;return <article className={String(m.sender_id)===userId?"mine":""} key={String(m.id)}><small>{String(sender?.full_name??sender?.email??(isAdmin?"Cliente":"LEGEND CLUB"))}</small><p>{String(m.body)}</p><time>{new Intl.DateTimeFormat("es-BO",{dateStyle:"short",timeStyle:"short",timeZone:"America/La_Paz"}).format(new Date(String(m.created_at)))}</time></article>})}</div>{selected&&<form className="chat-compose" onSubmit={send}><textarea name="body" maxLength={2000} placeholder="Escribe un mensaje" required/><button disabled={busy}><Send/> Enviar</button>{error&&<small>{error}</small>}</form>}</section></div></main>}
