"use client";

import {FormEvent,useState} from "react";
import type {ReactNode} from "react";
import {useRouter} from "next/navigation";
import {BadgeDollarSign,Gift,Landmark,Percent,UserRoundCog} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {DashboardModal} from "@/components/dashboard-modal";

type Row=Record<string,unknown>&{id?:string};
type Props={settings:Row|null;rewards:Row[];promotions:Row[];expenses:Row[];payouts:Row[];barbers:Row[];products:Row[];cashiers:Row[]};

export function AdminProgram({settings,rewards,promotions,expenses,payouts,barbers,products,cashiers}:Props){
 const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 async function rpc(name:string,args:Row,success:string){setBusy(true);setError("");setMessage("");const{error}=await createClient().rpc(name,args);setBusy(false);if(error)return setError(error.message);setMessage(success);router.refresh();}
 async function update(table:string,payload:Row,match:{column:string;value:unknown},success:string){setBusy(true);setError("");const{error}=await createClient().from(table).update(payload).eq(match.column,match.value);setBusy(false);if(error)return setError(error.message);setMessage(success);router.refresh();}
 async function cashier(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await rpc("set_cashier_role",{target_email:String(f.get("email")),enabled:true},"Acceso de caja habilitado.");}
 async function loyalty(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await update("loyalty_settings",{service_points:Number(f.get("service_points")),product_amount_per_point:Number(f.get("product_amount_per_point")),welcome_points:Number(f.get("welcome_points")),referral_referrer_points:Number(f.get("referral_referrer_points")),referral_referred_points:Number(f.get("referral_referred_points")),points_expiry_months:Number(f.get("points_expiry_months")),streak_visits:Number(f.get("streak_visits")),streak_days:Number(f.get("streak_days")),streak_bonus_points:Number(f.get("streak_bonus_points")),updated_at:new Date().toISOString()},{column:"id",value:true},"Reglas de fidelización actualizadas.");}
 async function addReward(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);const{error}=await createClient().from("rewards").insert({name:String(f.get("name")),description:String(f.get("description")??""),points_cost:Number(f.get("points_cost")),reward_type:String(f.get("reward_type")),reward_value:Number(f.get("reward_value")),max_discount:Number(f.get("max_discount"))||null,active:true});setBusy(false);if(error)return setError(error.message);setMessage("Recompensa creada.");router.refresh();}
 async function addPromotion(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);const{error}=await createClient().from("promotions").insert({name:String(f.get("name")),code:String(f.get("code")).trim().toUpperCase(),description:String(f.get("description")??""),discount_type:String(f.get("discount_type")),discount_value:Number(f.get("discount_value")),max_discount:Number(f.get("max_discount"))||null,starts_at:String(f.get("starts_at")||"")||null,ends_at:String(f.get("ends_at")||"")||null,usage_limit:Number(f.get("usage_limit"))||null,active:true});setBusy(false);if(error)return setError(error.message);setMessage("Promoción creada.");router.refresh();}
 async function adjustPoints(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await rpc("admin_adjust_loyalty",{target_email:String(f.get("email")),point_delta:Number(f.get("points")),adjustment_reason:String(f.get("reason"))},"Saldo ajustado con trazabilidad.");}
 async function payout(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await rpc("create_barber_payout",{target_barber:String(f.get("barber_id")),start_date:String(f.get("start_date")),end_date:String(f.get("end_date"))},"Liquidación preparada.");}
 async function rates(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const type=String(f.get("type"));await update(type==="barber"?"barber_profiles":"products",type==="barber"?{commission_percent:Number(f.get("percent"))}:{incentive_percent:Number(f.get("percent"))},{column:"id",value:String(f.get("target_id"))},"Porcentaje actualizado.");}
 return <div className="admin-panel program-panel"><div className="admin-title"><Landmark/><div><p>CAJA Y FIDELIZACIÓN</p><h1>Programa comercial</h1></div></div>{error&&<p className="admin-error">{error}</p>}{message&&<p className="admin-message">{message}</p>}
  <div className="program-grid">
   <ProgramCard icon={<UserRoundCog/>} title="Acceso de caja" stat={`${cashiers.length} activos`}><DashboardModal title="Habilitar cajero" description="La cuenta debe haber ingresado con Google al menos una vez." triggerLabel="Nuevo cajero"><form className="admin-form" onSubmit={cashier}><label className="wide">Correo Google<input name="email" type="email" required/></label><button className="button button-dark wide" disabled={busy}>Habilitar cajero</button></form></DashboardModal><div className="admin-list">{cashiers.map(c=><article key={String(c.id)}><div><strong>{String(c.email)}</strong><span>{String(c.full_name??"Cajero")}</span></div><button onClick={()=>rpc("set_cashier_role",{target_email:String(c.email),enabled:false},"Acceso retirado.")}>Retirar</button></article>)}</div></ProgramCard>
   <ProgramCard icon={<Gift/>} title="Reglas de puntos" stat={`${String(settings?.service_points??10)} pts/servicio`}><DashboardModal title="Configurar fidelización" description="Estos valores controlan puntos, referidos, vencimiento y rachas." triggerLabel="Editar reglas" size="large"><form className="admin-form" onSubmit={loyalty}><label>Puntos por servicio<input name="service_points" type="number" min="0" defaultValue={Number(settings?.service_points??10)}/></label><label>Bs por punto de producto<input name="product_amount_per_point" type="number" min="1" defaultValue={Number(settings?.product_amount_per_point??10)}/></label><label>Bienvenida<input name="welcome_points" type="number" min="0" defaultValue={Number(settings?.welcome_points??5)}/></label><label>Quien refiere<input name="referral_referrer_points" type="number" min="0" defaultValue={Number(settings?.referral_referrer_points??20)}/></label><label>Nuevo referido<input name="referral_referred_points" type="number" min="0" defaultValue={Number(settings?.referral_referred_points??10)}/></label><label>Vencimiento (meses)<input name="points_expiry_months" type="number" min="1" defaultValue={Number(settings?.points_expiry_months??12)}/></label><label>Visitas para racha<input name="streak_visits" type="number" min="2" defaultValue={Number(settings?.streak_visits??3)}/></label><label>Días de racha<input name="streak_days" type="number" min="1" defaultValue={Number(settings?.streak_days??35)}/></label><label>Bonificación racha<input name="streak_bonus_points" type="number" min="0" defaultValue={Number(settings?.streak_bonus_points??5)}/></label><button className="button button-dark wide" disabled={busy}>Guardar reglas</button></form></DashboardModal></ProgramCard>
   <ProgramCard icon={<Gift/>} title="Recompensas" stat={`${rewards.filter(r=>r.active).length} activas`}><DashboardModal title="Nueva recompensa" triggerLabel="Crear recompensa"><form className="admin-form" onSubmit={addReward}><label>Nombre<input name="name" required/></label><label>Costo en puntos<input name="points_cost" type="number" min="1" required/></label><label className="wide">Descripción<input name="description"/></label><label>Tipo<select name="reward_type"><option value="percent_discount">Descuento porcentual</option><option value="fixed_discount">Descuento fijo</option></select></label><label>Valor<input name="reward_value" type="number" min="0" step="0.5" required/></label><label>Máximo Bs<input name="max_discount" type="number" min="0" step="0.5"/></label><button className="button button-dark wide" disabled={busy}>Crear</button></form></DashboardModal><div className="admin-list">{rewards.map(r=><article key={String(r.id)}><div><strong>{String(r.name)}</strong><span>{String(r.points_cost)} puntos · {r.active?"activa":"inactiva"}</span></div><button onClick={()=>update("rewards",{active:!r.active},{column:"id",value:r.id},"Recompensa actualizada.")}>{r.active?"Desactivar":"Activar"}</button></article>)}</div></ProgramCard>
   <ProgramCard icon={<Percent/>} title="Promociones" stat={`${promotions.filter(p=>p.active).length} activas`}><DashboardModal title="Nueva promoción" description="Configura vigencia, límite y tope financiero." triggerLabel="Crear promoción" size="large"><form className="admin-form" onSubmit={addPromotion}><label>Nombre<input name="name" required/></label><label>Código<input name="code" required placeholder="LEGEND20"/></label><label>Tipo<select name="discount_type"><option value="percent">Porcentaje</option><option value="fixed">Monto fijo</option></select></label><label>Valor<input name="discount_value" type="number" min="0.5" step="0.5" required/></label><label>Tope Bs<input name="max_discount" type="number" min="0" step="0.5"/></label><label>Límite de usos<input name="usage_limit" type="number" min="1"/></label><label>Inicio<input name="starts_at" type="datetime-local"/></label><label>Fin<input name="ends_at" type="datetime-local"/></label><label className="wide">Descripción<input name="description"/></label><button className="button button-dark wide" disabled={busy}>Crear promoción</button></form></DashboardModal><div className="admin-list">{promotions.map(p=><article key={String(p.id)}><div><strong>{String(p.name)} · {String(p.code)}</strong><span>{String(p.usage_count)} usos · {p.active?"activa":"inactiva"}</span></div><button onClick={()=>update("promotions",{active:!p.active},{column:"id",value:p.id},"Promoción actualizada.")}>{p.active?"Desactivar":"Activar"}</button></article>)}</div></ProgramCard>
   <ProgramCard icon={<BadgeDollarSign/>} title="Control financiero" stat="Auditable"><div className="dash-action-stack"><DashboardModal title="Ajustar puntos" description="Todo ajuste queda registrado con correo y motivo." triggerLabel="Ajustar puntos" variant="secondary"><form className="admin-form" onSubmit={adjustPoints}><label>Correo<input name="email" type="email" required/></label><label>Puntos (+ o -)<input name="points" type="number" required/></label><label className="wide">Motivo<input name="reason" required/></label><button className="button button-dark wide" disabled={busy}>Registrar ajuste</button></form></DashboardModal><DashboardModal title="Configurar porcentajes" triggerLabel="Editar porcentajes" variant="secondary"><form className="admin-form" onSubmit={rates}><label>Tipo<select name="type"><option value="barber">Comisión peluquero</option><option value="product">Incentivo producto</option></select></label><label>Elemento<select name="target_id">{barbers.map(b=><option key={String(b.id)} value={String(b.id)}>{String(b.display_name)}</option>)}{products.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select></label><label>Porcentaje<input name="percent" type="number" min="0" max="100" step="0.5" defaultValue="50"/></label><button className="button button-dark wide" disabled={busy}>Actualizar</button></form></DashboardModal></div></ProgramCard>
   <ProgramCard icon={<BadgeDollarSign/>} title="Liquidaciones" stat={`${payouts.length} registros`}><DashboardModal title="Preparar liquidación" description="Incluye comisiones, incentivos y gastos aprobados sin duplicarlos." triggerLabel="Nueva liquidación"><form className="admin-form" onSubmit={payout}><label>Peluquero<select name="barber_id">{barbers.map(b=><option key={String(b.id)} value={String(b.id)}>{String(b.display_name)}</option>)}</select></label><label>Desde<input name="start_date" type="date" required/></label><label>Hasta<input name="end_date" type="date" required/></label><button className="button button-dark wide" disabled={busy}>Preparar</button></form></DashboardModal><div className="admin-list">{payouts.map(p=><article key={String(p.id)}><div><strong>{String((p.barber_profiles as Row|null)?.display_name)} · Bs {String(p.total_amount)}</strong><span>{String(p.period_start)} — {String(p.period_end)} · {String(p.status)}</span></div>{p.status==="approved"&&<button onClick={()=>rpc("mark_payout_paid",{target_payout:p.id},"Liquidación pagada.")}>Marcar pagada</button>}</article>)}</div></ProgramCard>
   <ProgramCard icon={<BadgeDollarSign/>} title="Gastos del equipo" stat={`${expenses.filter(e=>e.status==="pending").length} pendientes`}><div className="admin-list">{expenses.length?expenses.map(e=><article key={String(e.id)}><div><strong>{String((e.barber_profiles as Row|null)?.display_name)} · {String(e.concept)}</strong><span>Bs {String(e.amount)} · {String(e.status)}</span></div>{e.status==="pending"&&<div className="dash-row-actions"><button onClick={()=>rpc("review_barber_expense",{target_expense:e.id,next_status:"approved"},"Gasto aprobado.")}>Aprobar</button><button onClick={()=>rpc("review_barber_expense",{target_expense:e.id,next_status:"rejected"},"Gasto rechazado.")}>Rechazar</button></div>}</article>):<p className="admin-help">No hay gastos.</p>}</div></ProgramCard>
  </div>
 </div>;
}

function ProgramCard({icon,title,stat,children}:{icon:ReactNode;title:string;stat:string;children:ReactNode}){return <section className="program-card"><header><div className="portal-title">{icon}<h2>{title}</h2></div><span>{stat}</span></header>{children}</section>}
