"use client";

import {FormEvent,useState} from "react";
import type {ReactNode} from "react";
import {useRouter} from "next/navigation";
import {BadgeDollarSign,Gift,Landmark,Percent} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {DashboardModal} from "@/components/dashboard-modal";
import { clearFormErrors, dispatchDashboardError, dispatchDashboardSuccess, reportFormError } from "@/lib/form-feedback";

type Row=Record<string,unknown>&{id?:string};
type Props={settings:Row|null;rewards:Row[];promotions:Row[];expenses:Row[];payouts:Row[];barbers:Row[];products:Row[]};

export function AdminProgram({settings,rewards,promotions,barbers,products}:Props){
 const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 function fail(message:string){setError(message);dispatchDashboardError(message);}
 function finish(success:string){setError("");dispatchDashboardSuccess(success);router.refresh();}
 async function rpc(name:string,args:Row,success:string,form?:HTMLFormElement,preferredField?:string){if(form)clearFormErrors(form);setBusy(true);setError("");const{error}=await createClient().rpc(name,args);setBusy(false);if(error)return fail(reportFormError(form,error,preferredField));finish(success);}
 async function update(table:string,payload:Row,match:{column:string;value:unknown},success:string,form?:HTMLFormElement,preferredField?:string){if(form)clearFormErrors(form);setBusy(true);setError("");const{error}=await createClient().from(table).update(payload).eq(match.column,match.value);setBusy(false);if(error)return fail(reportFormError(form,error,preferredField));finish(success);}
 async function loyalty(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await update("loyalty_settings",{service_points:Number(f.get("service_points")),product_amount_per_point:Number(f.get("product_amount_per_point")),welcome_points:Number(f.get("welcome_points")),referral_referrer_points:Number(f.get("referral_referrer_points")),referral_referred_points:Number(f.get("referral_referred_points")),points_expiry_months:Number(f.get("points_expiry_months")),streak_visits:Number(f.get("streak_visits")),streak_days:Number(f.get("streak_days")),streak_bonus_points:Number(f.get("streak_bonus_points")),updated_at:new Date().toISOString()},{column:"id",value:true},"Reglas de fidelización actualizadas.",form);}
 async function addReward(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;clearFormErrors(form);const f=new FormData(form);setBusy(true);const{error}=await createClient().from("rewards").insert({name:String(f.get("name")),description:String(f.get("description")??""),points_cost:Number(f.get("points_cost")),reward_type:String(f.get("reward_type")),reward_value:Number(f.get("reward_value")),max_discount:Number(f.get("max_discount"))||null,active:true});setBusy(false);if(error)return fail(reportFormError(form,error,"name"));finish("Recompensa creada.");}
 async function addPromotion(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;clearFormErrors(form);const f=new FormData(form);setBusy(true);const{error}=await createClient().from("promotions").insert({name:String(f.get("name")),code:String(f.get("code")).trim().toUpperCase(),description:String(f.get("description")??""),discount_type:String(f.get("discount_type")),discount_value:Number(f.get("discount_value")),max_discount:Number(f.get("max_discount"))||null,starts_at:String(f.get("starts_at")||"")||null,ends_at:String(f.get("ends_at")||"")||null,usage_limit:Number(f.get("usage_limit"))||null,active:true});setBusy(false);if(error)return fail(reportFormError(form,error,"code"));finish("Promoción creada.");}
 async function adjustPoints(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await rpc("admin_adjust_loyalty",{target_email:String(f.get("email")),point_delta:Number(f.get("points")),adjustment_reason:String(f.get("reason"))},"Saldo ajustado con trazabilidad.",form,"email");}
 async function rates(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const type=String(f.get("type"));await update(type==="barber"?"barber_profiles":"products",type==="barber"?{commission_percent:Number(f.get("percent"))}:{incentive_percent:Number(f.get("percent"))},{column:"id",value:String(f.get("target_id"))},"Porcentaje actualizado.",form,"percent");}
 return <div className="admin-panel program-panel"><div className="admin-title"><Landmark/><div><p>CAJA Y FIDELIZACIÓN</p><h1>Programa comercial</h1></div></div>{error&&<p className="admin-error">{error}</p>}
  <div className="program-grid">
   <ProgramCard icon={<Gift/>} title="Reglas de puntos" stat={`${String(settings?.service_points??10)} pts/servicio`}><DashboardModal title="Configurar fidelización" description="Estos valores controlan puntos, referidos, vencimiento y rachas." triggerLabel="Editar reglas" size="large"><form className="admin-form" onSubmit={loyalty}><label>Puntos por servicio<input name="service_points" type="number" min="0" defaultValue={Number(settings?.service_points??10)}/></label><label>Bs por punto de producto<input name="product_amount_per_point" type="number" min="1" defaultValue={Number(settings?.product_amount_per_point??10)}/></label><label>Bienvenida<input name="welcome_points" type="number" min="0" defaultValue={Number(settings?.welcome_points??5)}/></label><label>Quien refiere<input name="referral_referrer_points" type="number" min="0" defaultValue={Number(settings?.referral_referrer_points??20)}/></label><label>Nuevo referido<input name="referral_referred_points" type="number" min="0" defaultValue={Number(settings?.referral_referred_points??10)}/></label><label>Vencimiento (meses)<input name="points_expiry_months" type="number" min="1" defaultValue={Number(settings?.points_expiry_months??12)}/></label><label>Visitas para racha<input name="streak_visits" type="number" min="2" defaultValue={Number(settings?.streak_visits??3)}/></label><label>Días de racha<input name="streak_days" type="number" min="1" defaultValue={Number(settings?.streak_days??35)}/></label><label>Bonificación racha<input name="streak_bonus_points" type="number" min="0" defaultValue={Number(settings?.streak_bonus_points??5)}/></label><button className="button button-dark wide" disabled={busy}>Guardar reglas</button></form></DashboardModal></ProgramCard>
   <ProgramCard icon={<Gift/>} title="Recompensas" stat={`${rewards.filter(r=>r.active).length} activas`}><DashboardModal title="Nueva recompensa" triggerLabel="Crear recompensa"><form className="admin-form" onSubmit={addReward}><label>Nombre<input name="name" required/></label><label>Costo en puntos<input name="points_cost" type="number" min="1" required/></label><label className="wide">Descripción<input name="description"/></label><label>Tipo<select name="reward_type"><option value="percent_discount">Descuento porcentual</option><option value="fixed_discount">Descuento fijo</option></select></label><label>Valor<input name="reward_value" type="number" min="0" step="0.5" required/></label><label>Máximo Bs<input name="max_discount" type="number" min="0" step="0.5"/></label><button className="button button-dark wide" disabled={busy}>Crear</button></form></DashboardModal><div className="admin-list">{rewards.map(r=><article key={String(r.id)}><div><strong>{String(r.name)}</strong><span>{String(r.points_cost)} puntos · {r.active?"activa":"inactiva"}</span></div><button onClick={()=>update("rewards",{active:!r.active},{column:"id",value:r.id},"Recompensa actualizada.")}>{r.active?"Desactivar":"Activar"}</button></article>)}</div></ProgramCard>
   <ProgramCard icon={<Percent/>} title="Promociones" stat={`${promotions.filter(p=>p.active).length} activas`}><DashboardModal title="Nueva promoción" description="Configura vigencia, límite y tope financiero." triggerLabel="Crear promoción" size="large"><form className="admin-form" onSubmit={addPromotion}><label>Nombre<input name="name" required/></label><label>Código<input name="code" required placeholder="LEGEND20"/></label><label>Tipo<select name="discount_type"><option value="percent">Porcentaje</option><option value="fixed">Monto fijo</option></select></label><label>Valor<input name="discount_value" type="number" min="0.5" step="0.5" required/></label><label>Tope Bs<input name="max_discount" type="number" min="0" step="0.5"/></label><label>Límite de usos<input name="usage_limit" type="number" min="1"/></label><label>Inicio<input name="starts_at" type="datetime-local"/></label><label>Fin<input name="ends_at" type="datetime-local"/></label><label className="wide">Descripción<input name="description"/></label><button className="button button-dark wide" disabled={busy}>Crear promoción</button></form></DashboardModal><div className="admin-list">{promotions.map(p=><article key={String(p.id)}><div><strong>{String(p.name)} · {String(p.code)}</strong><span>{String(p.usage_count)} usos · {p.active?"activa":"inactiva"}</span></div><button onClick={()=>update("promotions",{active:!p.active},{column:"id",value:p.id},"Promoción actualizada.")}>{p.active?"Desactivar":"Activar"}</button></article>)}</div></ProgramCard>
   <ProgramCard icon={<BadgeDollarSign/>} title="Control financiero" stat="Auditable"><div className="dash-action-stack"><DashboardModal title="Ajustar puntos" description="Todo ajuste queda registrado con correo y motivo." triggerLabel="Ajustar puntos" variant="secondary"><form className="admin-form" onSubmit={adjustPoints}><label>Correo<input name="email" type="email" required/></label><label>Puntos (+ o -)<input name="points" type="number" required/></label><label className="wide">Motivo<input name="reason" required/></label><button className="button button-dark wide" disabled={busy}>Registrar ajuste</button></form></DashboardModal><DashboardModal title="Configurar porcentajes" triggerLabel="Editar porcentajes" variant="secondary"><form className="admin-form" onSubmit={rates}><label>Tipo<select name="type"><option value="barber">Comisión peluquero</option><option value="product">Incentivo producto</option></select></label><label>Elemento<select name="target_id">{barbers.map(b=><option key={String(b.id)} value={String(b.id)}>{String(b.display_name)}</option>)}{products.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</select></label><label>Porcentaje<input name="percent" type="number" min="0" max="100" step="0.5" defaultValue="50"/></label><button className="button button-dark wide" disabled={busy}>Actualizar</button></form></DashboardModal></div></ProgramCard>
  </div>
 </div>;
}

function ProgramCard({icon,title,stat,children}:{icon:ReactNode;title:string;stat:string;children:ReactNode}){return <section className="program-card"><header><div className="portal-title">{icon}<h2>{title}</h2></div><span>{stat}</span></header>{children}</section>}
