"use client";

import {FormEvent,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {Banknote,CircleDollarSign,History,LockKeyhole,ReceiptText,Sparkles,WalletCards} from "lucide-react";
import {Brand} from "@/components/brand";
import {DashboardModal} from "@/components/dashboard-modal";
import {ModeSwitcher} from "@/components/mode-switcher";
import {createClient} from "@/lib/supabase/client";

type Row=Record<string,unknown>&{id:string};
type Capabilities={isAdmin:boolean;isSuperadmin:boolean;isCashier:boolean;barber:{id:string;display_name:string}|null};
type Props={userEmail:string;capabilities:Capabilities;shift:Row|null;services:Row[];barbers:Row[];products:Row[];clients:Row[];appointments:Row[];sales:Row[]};

export function CashierPanel({userEmail,capabilities,shift,services,barbers,products,clients,appointments,sales}:Props){
 const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[result,setResult]=useState<Record<string,unknown>|null>(null);
 async function call(name:string,args:Record<string,unknown>){setBusy(true);setError("");const{data,error}=await createClient().rpc(name,args);setBusy(false);if(error){setError(error.message);return null;}return data;}
 async function open(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);if(await call("open_cash_shift",{opening:Number(f.get("opening")),shift_notes:String(f.get("notes")??"")||null}))router.refresh();}
 async function sell(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const data=await call("register_counter_sale",{target_appointment_id:String(f.get("appointment_id")??"")||null,target_client_id:String(f.get("client_id")??"")||null,guest_name:String(f.get("guest_name")??"")||null,guest_phone:String(f.get("guest_phone")??"")||null,target_barber_id:String(f.get("barber_id")??"")||null,target_service_id:String(f.get("service_id")??"")||null,target_product_id:String(f.get("product_id")??"")||null,product_quantity:Number(f.get("quantity")??1),recommended_by_barber_id:String(f.get("recommended_by")??"")||null,manual_discount:Number(f.get("discount")??0),payment_method:String(f.get("payment_method")??"cash"),payment_reference:String(f.get("payment_reference")??"")||null,provided_referral_code:String(f.get("referral_code")??"")||null,redemption_code:String(f.get("redemption_code")??"")||null,promotion_code:String(f.get("promotion_code")??"")||null});if(data){setResult(data as Record<string,unknown>);router.refresh();}}
 async function movement(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);if(await call("record_cash_movement",{movement_kind:String(f.get("kind")),movement_amount:Number(f.get("amount")),payment_method:String(f.get("method")),movement_reason:String(f.get("reason"))}))router.refresh();}
 async function close(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const data=await call("close_cash_shift",{counted:Number(f.get("counted")),shift_notes:String(f.get("notes")??"")||null});if(data){setResult(data as Record<string,unknown>);router.refresh();}}
 async function reverseSale(id:string){const reason=window.prompt("Motivo obligatorio de la devolución o anulación:");if(reason?.trim()&&await call("reverse_counter_sale",{target_sale_id:id,reversal_reason:reason.trim()}))router.refresh();}
 const opening=Number(shift?.opening_amount??0);const todayTotal=sales.reduce((sum,sale)=>sum+Number(sale.paid_total),0);
 return <main className="admin-shell dash-workspace cashier-shell">
  <header className="admin-header dash-header"><div className="dash-brand"><Brand/><span className="dash-live"><i/> CAJA CONECTADA</span></div><ModeSwitcher current="cashier" isAdmin={capabilities.isAdmin} hasBarber={Boolean(capabilities.barber)} isCashier showClient={!capabilities.isSuperadmin}/><div className="dash-user"><span className="dash-avatar">{userEmail.slice(0,2).toUpperCase()}</span><span>{userEmail}<small>Operador de caja</small></span><Link href="/">Sitio público</Link></div></header>
  <div className="admin-layout cashier-layout"><aside className="admin-nav dash-sidebar"><div className="dash-sidebar-head"><p>TERMINAL POS</p></div><nav><a href="#operacion"><WalletCards/><span>Operación</span><i/></a><a href="#ventas"><History/><span>Historial</span></a></nav><div className="dash-sidebar-foot"><Link href="/"><Sparkles/><span>Web pública</span></Link></div></aside>
   <section className="cashier-content" id="operacion"><div className="dash-page-heading"><div className="admin-title"><WalletCards/><div><p>OPERACIÓN PRESENCIAL</p><h1>Terminal de caja</h1></div></div><span className={`dash-status-pill ${shift?"online":"offline"}`}><i/>{shift?"Turno abierto":"Turno cerrado"}</span></div>
    {error&&<p className="admin-error">{error}</p>}{result&&<div className="admin-message"><strong>Operación completada.</strong>{"receipt_id" in result&&<Link href={`/comprobante/${String(result.receipt_id)}`}> Ver comprobante #{String(result.receipt_number)}</Link>}{Boolean(result.claim_code)&&<span> Código: <b>{String(result.claim_code)}</b></span>}</div>}
    {!shift?<section className="admin-panel cashier-welcome"><div className="cashier-orb"><LockKeyhole/></div><p className="eyebrow">TERMINAL BLOQUEADA</p><h2>Abre un turno para comenzar.</h2><p>El sistema conciliará automáticamente efectivo, pagos digitales, ingresos y egresos.</p><DashboardModal title="Abrir turno de caja" description="Registra el efectivo disponible al iniciar." triggerLabel="Abrir terminal" triggerIcon={<LockKeyhole/>}><form className="admin-form" onSubmit={open}><label>Monto inicial Bs<input name="opening" type="number" min="0" step="0.5" defaultValue="0" required/></label><label>Observación<input name="notes"/></label><button className="button button-dark wide" disabled={busy}>Confirmar apertura</button></form></DashboardModal></section>:<>
     <div className="cashier-kpis"><article><small>VENTAS REGISTRADAS</small><strong>{sales.length}</strong><span>operaciones recientes</span></article><article><small>INGRESOS</small><strong>Bs {todayTotal.toFixed(2)}</strong><span>ventas confirmadas</span></article><article><small>FONDO INICIAL</small><strong>Bs {opening.toFixed(2)}</strong><span>turno actual</span></article></div>
     <div className="cashier-command-grid"><section className="admin-panel command-card featured"><div className="command-icon"><ReceiptText/></div><small>ACCIÓN PRINCIPAL</small><h2>Nueva venta</h2><p>Registra servicios, productos, descuentos, canjes y pagos desde un flujo enfocado.</p><DashboardModal title="Registrar venta o atención" description="Puedes cobrar una cita existente o una atención sin reserva." triggerLabel="Iniciar cobro" triggerIcon={<CircleDollarSign/>} size="large"><SaleForm appointments={appointments} clients={clients} services={services} barbers={barbers} products={products} busy={busy} onSubmit={sell}/></DashboardModal></section>
      <section className="admin-panel command-card"><div className="command-icon"><Banknote/></div><small>CONTROL DE CAJA</small><h2>Movimiento manual</h2><p>Registra ingresos, egresos o ajustes con su justificación.</p><DashboardModal title="Registrar movimiento" triggerLabel="Nuevo movimiento" variant="secondary"><MovementForm busy={busy} onSubmit={movement}/></DashboardModal></section>
      <section className="admin-panel command-card danger-zone"><div className="command-icon"><LockKeyhole/></div><small>CONCILIACIÓN</small><h2>Cerrar turno</h2><p>Cuenta el efectivo y revisa automáticamente cualquier diferencia.</p><DashboardModal title="Cerrar y conciliar caja" description="Esta acción finalizará el turno actual." triggerLabel="Cerrar terminal" variant="ghost"><form className="admin-form" onSubmit={close}><label className="wide">Efectivo contado Bs<input name="counted" type="number" min="0" step="0.5" required/></label><label className="wide">Observación<input name="notes"/></label><button className="button button-dark wide" disabled={busy}>Cerrar y conciliar</button></form></DashboardModal></section></div>
     <section className="admin-panel" id="ventas"><div className="dash-list-head"><div><small>TRAZABILIDAD</small><h2>Últimas ventas</h2></div><History/></div><div className="admin-list">{sales.length?sales.map(s=>{const receipt=Array.isArray(s.receipts)?s.receipts[0]:s.receipts as {id?:string;number?:number}|null;return <article key={s.id}><div><strong>{String((s.profiles as {full_name?:string}|null)?.full_name??s.guest_name??"Cliente")}</strong><span>Bs {String(s.paid_total)} · descuento Bs {String(s.discount_total)} · comisión Bs {String(s.barber_commission_total)}</span></div><div className="dash-row-actions">{receipt?.id&&<Link href={`/comprobante/${receipt.id}`}>#{String(receipt.number)}</Link>}<button disabled={busy} onClick={()=>reverseSale(String(s.id))}>Revertir</button></div></article>}):<p className="admin-help">Todavía no hay ventas en caja.</p>}</div></section>
    </>}
   </section>
  </div>
 </main>;
}

function SaleForm({appointments,clients,services,barbers,products,busy,onSubmit}:{appointments:Row[];clients:Row[];services:Row[];barbers:Row[];products:Row[];busy:boolean;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <form className="admin-form" onSubmit={onSubmit}><label className="wide">Cita existente<select name="appointment_id" defaultValue=""><option value="">Atención sin reserva</option>{appointments.map(a=><option key={a.id} value={a.id}>{new Intl.DateTimeFormat("es-BO",{timeStyle:"short",timeZone:"America/La_Paz"}).format(new Date(String(a.starts_at)))} · {String(a.service_name_snapshot)} · {String((a.profiles as {full_name?:string}|null)?.full_name??"Cliente")}</option>)}</select></label><label>Cliente registrado<select name="client_id"><option value="">Cliente invitado</option>{clients.map(c=><option key={c.id} value={c.id}>{String(c.full_name??c.email)}</option>)}</select></label><label>Nombre invitado<input name="guest_name"/></label><label>Teléfono invitado<input name="guest_phone" inputMode="tel"/></label><label>Código referido<input name="referral_code" placeholder="LC-..."/></label><label>Servicio<select name="service_id"><option value="">Sin servicio</option>{services.map(s=><option key={s.id} value={s.id}>{String(s.name)} · Bs {String(s.price)}</option>)}</select></label><label>Peluquero<select name="barber_id"><option value="">Seleccionar</option>{barbers.map(b=><option key={b.id} value={b.id}>{String(b.display_name)} · {String(b.commission_percent)}%</option>)}</select></label><label>Producto<select name="product_id"><option value="">Sin producto</option>{products.map(p=><option key={p.id} value={p.id}>{String(p.name)} · Bs {String(p.price)} · stock {String(p.stock)}</option>)}</select></label><label>Cantidad<input name="quantity" type="number" min="1" max="20" defaultValue="1"/></label><label>Recomendado por<select name="recommended_by"><option value="">Sin recomendador</option>{barbers.map(b=><option key={b.id} value={b.id}>{String(b.display_name)}</option>)}</select></label><label>Descuento manual Bs<input name="discount" type="number" min="0" step="0.5" defaultValue="0"/></label><label>Código de promoción<input name="promotion_code"/></label><label>Código de canje<input name="redemption_code"/></label><label>Forma de pago<select name="payment_method" defaultValue="cash"><option value="cash">Efectivo</option><option value="qr">QR</option><option value="transfer">Transferencia</option><option value="card">Tarjeta</option><option value="other">Otro</option></select></label><label>Referencia<input name="payment_reference"/></label><button className="button button-dark wide" disabled={busy}><CircleDollarSign/> Confirmar pago y emitir comprobante</button></form>}
function MovementForm({busy,onSubmit}:{busy:boolean;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <form className="admin-form" onSubmit={onSubmit}><label>Tipo<select name="kind"><option value="income">Ingreso</option><option value="expense">Egreso</option><option value="adjustment">Ajuste</option></select></label><label>Monto Bs<input name="amount" type="number" min="0.5" step="0.5" required/></label><label>Método<select name="method"><option value="cash">Efectivo</option><option value="qr">QR</option><option value="transfer">Transferencia</option></select></label><label>Motivo<input name="reason" required/></label><button className="button button-dark wide" disabled={busy}>Registrar movimiento</button></form>}
